apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
spec:
  sourceNamespaces:
    - my-namespace
    - my-other-namespace
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  roles:
    - name: my-role
      policies:
        - p, proj:my-project:my-role, applications, get, my-project/my-namespace/app-prefix-*, allow
